// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozieswtymloegmxqaxds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96aWVzd3R5bWxvZWdteHFheGRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMTU4MjMsImV4cCI6MjA2NDU5MTgyM30.haB4n9m-ZmlU6eOnc27CnuABWJjCv9N_E6w6-AWxONI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);